const GET_FRIEND = "GET_FRIEND";
const ADD_FRIEND = 'ADD_FRIEND';
const ADD_FAV_FRIEND = 'ADD_FAV_FRIEND';
const REMOVE_FAV_FRIEND = 'REMOVE_FAV_FRIEND';
const DELETE_FRIEND = 'DELETE_FRIEND';
const SHOW_LOADER = 'SHOW_LOADER';

export { ADD_FRIEND, ADD_FAV_FRIEND, REMOVE_FAV_FRIEND, DELETE_FRIEND, GET_FRIEND, SHOW_LOADER }